create table if not exists raw_fenster_subscriptions (
    id varchar,
    ts timestamptz,
    type varchar,
    cid varchar,
    mail varchar,
    signup_ts timestamptz,
    ctry varchar,
    state varchar,
    zip varchar,
    plan varchar,
    ccy varchar,
    price double,
    tax double,
    vat_id varchar,
    campaign_src varchar,
    utm_medium varchar,
    utm_campaign varchar,
    browser varchar,
    os varchar,
    screen_res varchar,
    lang varchar,
    tz varchar,
    legacy_flag boolean,
    migrated_from varchar,
    batch_id varchar,
    row_hash varchar
);
