create table if not exists raw_apfel_subscriptions (
    event_id varchar,
    affiliate_id varchar,
    event_timestamp timestamptz,
    event_type varchar,
    customer_uuid varchar,
    customer_email varchar,
    customer_created_at timestamptz,
    country_code varchar,
    region varchar,
    city varchar,
    postal_code varchar,
    subscription_type varchar,
    renewal_period varchar,
    currency varchar,
    amount double,
    tax_amount double,
    discount_code varchar,
    device_type varchar,
    app_version varchar,
    session_id varchar,
    internal_ref varchar,
    processing_status varchar
);
